### ISSUE TITLE
Docker: users.json does not update in `--detach` mode

### ISSUE THREAD

**Issue by ellidi** [RblSb/SyncTube#45]
Running in docker.
Everything works as it should, but I cannot log in to my created admin account.
The "Login" button under "Accounts" in the settings pane does not do anything at all on 3 different browsers.
Am I missing something?

**Comment by RblSb** [comment]
If you created account and have `user/users.json` file, you can enter your registered admin name to login input, and then you should see password input, if your name is same and registered user exists.

**Comment by ellidi** [comment]
Oh, I see the problem, users.json is reset every time I restart the container...

**Comment by ellidi** [comment]
After a few /addAdmin -> restart container attempts, it finally stuck.

**Comment by RblSb** [comment]
Are tou runned it from cli, as in readme, or some other way?

**Comment by ellidi** [comment]
`docker run -d -it -p 4200:4200 -v /[...]`

**Comment by ellidi** [comment]
`docker run --rm -it -p 4200:4200 -v /[...]` makes the config stick.
The thing is that as soon as the `/exit` command is entered, the container shuts down.
I just want it to run in the background.
It seems the only way to get `users.json`to stick, is to do it this way,
then `/exit`, and then run again with `-d`

**Comment by RblSb** [comment]
Thanks for info and words, will try to repro it later and check if there is some other docker flags to keep state on exit with detached mode. Maybe i write users file only on exit from memory, and exit signal is not sended in this corner case, hm.
I mostly use this project as `screen -S synctube node build/server.js`, so docker setup is not much tested, and was added by users initiative, but i want to keep it in good state, since containers is useful too.

**Comment by RblSb** [comment]
I tested it like this:
```
docker run -d --rm -it -p 4200:4200 -v ${PWD}/user:/usr/src/app/user synctube
docker attach active_container_id_here
```
And `/exit` after `/addAdmin` shows `Saving state...` in output and saves things correctly, is this same for you?
Or, if you got state.json/users.json removed on next container start, then it looks like problem with attached `--volume` folder.

**Comment by RblSb** [comment]
Will close it since i cannot repro, so if i ignore it, maybe it will go away.

**Comment by AnonymousX86** [comment]
I have the same issue.

I've tried to run with compose:
```yaml
---
name: synctube

services:
  synctube:
    build:
      context: https://github.com/RblSb/SyncTube.git
      network: host
    container_name: synctube
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: ${BASE_DOMAIN}
    env_file:
      - .env
    volumes:
      - ./user:/usr/src/app/user
    expose:
      - '4200/tcp' # HTTP web GUI
    networks:
      - frontend
    labels:
      diun.enable: true
      traefik.enable: true
      traefik.http.routers.synctube.rule: 'Host(`${BASE_DOMAIN}`)'
      traefik.http.routers.synctube.tls.certresolver: cloudflare
      traefik.http.routers.synctube.middlewares: authentik@docker
      traefik.http.services.synctube.loadbalancer.server.port: 4200

networks:
  frontend:
    external: true
```

I've also tried to use the `docker run` method:
```sh
sudo docker run --rm -it -v ${PWD}/user:/usr/src/app/user synctube
```

**And** `docker compose run` method:
```sh
sudo docker compose run --rm -it -v ${PWD}/user:/usr/src/app/user synctube
```

Each time I create the Admin account, restart, and my account is gone. Both for `/addAdmin` CLI and web GUI. No JSON file is created, the `user/` directory is empty.
