### ISSUE TITLE
Button margins 

### ISSUE THREAD

**Issue by aus-tin** [RblSb/SyncTube#7]
Hi! Sorry for another issue but it seems like one of the button styles fixes was imported from an older commit (probably one of the previous --amend's)

currently the styling looks like this:

```CSS
button:not(:first-child) {
    margin-left: .5rem;
}
```

though this causes problems with the alignment of the "users online" button in the chat (by adding a .5rem margin to the left)

 changing the styling to this will fix the problem:

```CSS
button:not(:last-child) {
    margin-right: .5rem;
}
```
